const meals = [
  {
    name: "Jollof Rice",
    desc: "Spicy Ghanaian jollof with fried plantains",
    price: 25,
    image: "images/jollof.jpg",
    category: "Rice Dishes",
  },
  {
    name: "Waakye",
    desc: "Delicious waakye with egg and wele",
    price: 28,
    image: "images/waakye.jpg",
    category: "Rice Dishes",
  },
  {
    name: "Fufu with Light Soup",
    desc: "Traditional fufu served with light goat soup",
    price: 30,
    image: "images/fufu-light-soup.jpg",
    category: "Local Dishes",
  },
  {
    name: "Banku & Tilapia",
    desc: "Grilled tilapia with spicy pepper and banku",
    price: 35,
    image: "images/banku.jpg",
    category: "Local Dishes",
  },
  {
    name: "Fried Yam & Shito",
    desc: "Crispy yam served with turkey tail and shito",
    price: 22,
    image: "images/fried-yam.jpg",
    category: "Local Dishes",
  },
  {
    name: "Kenkey & Fish",
    desc: "Kenkey with fried fish, shito, and fresh pepper",
    price: 20,
    image: "images/kenkey-fish.jpg",
    category: "Local Dishes",
  },
  {
    name: "Plain Rice & Stew",
    desc: "White rice with chicken stew and salad",
    price: 24,
    image: "images/plain-rice.jpg",
    category: "Rice Dishes",
  },
  {
    name: "Ampesi & Kontomire Stew",
    desc: "Boiled yam with kontomire and eggs",
    price: 23,
    image: "images/ampesi.jpg",
    category: "Local Dishes",
  },
  {
    name: "Indomie & Egg",
    desc: "Hot instant noodles topped with egg and veggies",
    price: 18,
    image: "images/indomie.jpg",
    category: "Snacks",
  },
  {
    name: "Angwamo",
    desc: "Oil rice with sardines and fried eggs",
    price: 20,
    image: "images/angwamo.jpg",
    category: "Rice Dishes",
  },
  {
    name: "Spring Rolls",
    desc: "Crispy vegetarian spring rolls",
    price: 15,
    image: "images/spring-rolls.jpg",
    category: "Snacks",
  },
  {
    name: "Shawarma",
    desc: "Chicken shawarma wrap with creamy sauce",
    price: 27,
    image: "images/shawarma.jpg",
    category: "Snacks",
  },
  {
    name: "Kelewele",
    desc: "Spicy fried ripe plantains",
    price: 12,
    image: "images/kelewele.jpg",
    category: "Snacks",
  },
  {
    name: "Sobolo",
    desc: "Chilled hibiscus drink served fresh",
    price: 8,
    image: "images/sobolo.jpg",
    category: "Drinks",
  },
  {
    name: "Pineapple Juice",
    desc: "Freshly blended pineapple juice",
    price: 10,
    image: "images/pineapple-juice.jpg",
    category: "Drinks",
  },
  {
    name: "Meat Pie",
    desc: "Golden baked meat pies with minced beef",
    price: 10,
    image: "images/meat-pie.jpg",
    category: "Snacks",
  },
  {
    name: "Fried Rice",
    desc: "Ghana-style fried rice with chicken",
    price: 26,
    image: "images/fried-rice.jpg",
    category: "Rice Dishes",
  },
  {
    name: "Pizza Slice",
    desc: "Cheesy beef pizza slice",
    price: 18,
    image: "images/pizza.jpg",
    category: "Snacks",
  },
  {
    name: "Kebab",
    desc: "Spicy beef kebab",
    price: 25,
    image: "images/kebab.jpg",
    category: "Snacks",
  },
  {
    name: "Tom Brown",
    desc: "Hot breakfast porridge with milk",
    price: 12,
    image: "images/tom-brown.jpg",
    category: "Breakfast",
  },
  
];  

fetch("http://localhost:5000/api/food")
  .then(res => res.json())
  .then(data => console.log(data));